language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

install: true

before_script:
  - go mod download
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.5

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: go build
    - stage: "Tests"
      name: "Unit Tests"
      script: go test ./... -coverprofile=coverage.txt -covermode=count
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: golangci-lint run
    - stage: "Release"
      name: "Release Binaries"
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux