language: go

go:
  - 1.11.x

install: true

env:
  - DEP_RELEASE_TAG=v0.5.0

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.5

jobs:
  include:
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: golangci-lint run
    - stage: "Tests"
      name: "Unit Tests"
      script: sh test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Release"
      name: "Release Binaries"
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux